# Generated by Django 5.0 on 2024-02-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_order_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('date_order', models.DateTimeField()),
                ('date_shipping', models.DateField()),
                ('time_shipping', models.TextField()),
                ('status', models.TextField()),
                ('adress', models.TextField()),
                ('comment', models.TextField()),
                ('pay_type', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.CreateModel(
            name='order_gym_eqw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
