# Generated by Django 5.0 on 2024-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_remove_cart_order_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contactphone',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='order_gym',
        ),
    ]
