# Generated by Django 5.0 on 2024-02-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_payment_delete_stuff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
