# Generated by Django 5.0 on 2024-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.IntegerField(null=True),
        ),
    ]
