# Generated by Django 5.0 on 2024-02-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_pay_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card_status',
        ),
    ]
