# Generated by Django 4.2.7 on 2024-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='days',
        ),
        migrations.AddField(
            model_name='order',
            name='date_return',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order_gym_eqw',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
